version: '3.8'

services:

  # --- MONGODB ---
  mongodb:
    image: mongo:6.0 # Dùng bản ổn định 6.0
    container_name: edurag-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      # Map thư mục 'MongoDB' ở máy thật vào nơi chứa dữ liệu trong Container
      - ./MongoDB:/data/db
    env_file:
      - .env
    environment:
      # Tạo user/pass mặc định cho DB (nên đổi nếu đưa lên production)
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INIT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INIT_PASS}

  # --- BACKEND ---
  backend:
    build: .
    container_name: edurag-backend
    command: uvicorn server.fastapi_run:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URL=mongodb://${MONGO_INIT_USER}:${MONGO_INIT_PASS}@mongodb:27017
      - DB_NAME=${DB_NAME}

    depends_on:
      - mongodb # Backend sẽ đợi Mongo chạy trước

  # --- FRONTEND ---
  frontend:
    build: .
    container_name: edurag-frontend
    command: streamlit run UI/streamlit_UI.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
    depends_on:
      - backend